name: Update CSV with Selenium

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行。適宜スケジュールを設定してください。
  push:
    branches:
      - main  # 適宜ブランチを指定してください。

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        sudo wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
        sudo wget -q https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        echo "ChromeDriver version: $CHROME_DRIVER_VERSION"

    - name: Ensure ChromeDriver is in PATH
      run: |
        export PATH=$PATH:/usr/local/bin
        echo $PATH  # 確認のためにPATHを出力

    - name: Run Selenium script
      env:
        DISPLAY: ":99"  # 仮想ディスプレイ環境を設定
        CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"
      run: |
        Xvfb :99 -ac &
        python .github/workflows/check_prices.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add buyback_prices.csv
        git commit -m 'Update buyback_prices.csv with Selenium results'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
